// js/demoData.js
// Test database. Fictional placeholder titles (not real releases — avoids any
// licensing question and makes it obvious at a glance which items are demo
// data). Used by home.js whenever the real library is empty, and by api.js
// as a search fallback before any provider API key is configured.
//
// Every item follows the Unified Media Item model (see docs/PROJECT.md §6):
//   id, provider, providerId, title, originalTitle, type, year, rating,
//   poster, backdrop, description, runtime, episodes, playtime

function poster(title) {
  return `https://placehold.co/300x450/242a36/eef1f6?text=${encodeURIComponent(title)}`;
}

function backdrop(title) {
  return `https://placehold.co/800x450/1c212b/eef1f6?text=${encodeURIComponent(title)}`;
}

export const demoData = [
  {
    id: 'demo-movie-1',
    provider: 'demo',
    providerId: 'demo-movie-1',
    title: 'The Last Signal',
    originalTitle: 'The Last Signal',
    type: 'movie',
    year: 2021,
    rating: 7.8,
    poster: poster('The Last Signal'),
    backdrop: backdrop('The Last Signal'),
    description: 'A stranded astronaut races to send one final message home before her ship runs out of power.',
    runtime: 118,
    episodes: null,
    playtime: null,
  },
  {
    id: 'demo-movie-2',
    provider: 'demo',
    providerId: 'demo-movie-2',
    title: 'Paper Lanterns',
    originalTitle: 'Paper Lanterns',
    type: 'movie',
    year: 2018,
    rating: 6.9,
    poster: poster('Paper Lanterns'),
    backdrop: backdrop('Paper Lanterns'),
    description: 'Three childhood friends reunite for one summer in their hometown before it changes forever.',
    runtime: 104,
    episodes: null,
    playtime: null,
  },
  {
    id: 'demo-movie-3',
    provider: 'demo',
    providerId: 'demo-movie-3',
    title: 'Iron Tide',
    originalTitle: 'Iron Tide',
    type: 'movie',
    year: 2023,
    rating: 8.2,
    poster: poster('Iron Tide'),
    backdrop: backdrop('Iron Tide'),
    description: 'A salvage crew uncovers something the ocean was never meant to give back.',
    runtime: 131,
    episodes: null,
    playtime: null,
  },
  {
    id: 'demo-series-1',
    provider: 'demo',
    providerId: 'demo-series-1',
    title: 'Northbound',
    originalTitle: 'Northbound',
    type: 'series',
    year: 2020,
    rating: 8.5,
    poster: poster('Northbound'),
    backdrop: backdrop('Northbound'),
    description: 'A small-town detective is pulled back to the case that ended her career fifteen years ago.',
    runtime: null,
    episodes: 24,
    playtime: null,
  },
  {
    id: 'demo-series-2',
    provider: 'demo',
    providerId: 'demo-series-2',
    title: 'The Quiet Office',
    originalTitle: 'The Quiet Office',
    type: 'series',
    year: 2022,
    rating: 7.1,
    poster: poster('The Quiet Office'),
    backdrop: backdrop('The Quiet Office'),
    description: 'A mockumentary following the most aggressively average marketing team in the country.',
    runtime: null,
    episodes: 18,
    playtime: null,
  },
  {
    id: 'demo-series-3',
    provider: 'demo',
    providerId: 'demo-series-3',
    title: 'Glasshouse',
    originalTitle: 'Glasshouse',
    type: 'series',
    year: 2024,
    rating: 8.9,
    poster: poster('Glasshouse'),
    backdrop: backdrop('Glasshouse'),
    description: 'Four families, one experimental apartment building, and a rule that no one can leave for a year.',
    runtime: null,
    episodes: 10,
    playtime: null,
  },
  {
    id: 'demo-anime-1',
    provider: 'demo',
    providerId: 'demo-anime-1',
    title: 'Starlight Relay',
    originalTitle: 'Sutaraito Rirē',
    type: 'anime',
    year: 2019,
    rating: 8.7,
    poster: poster('Starlight Relay'),
    backdrop: backdrop('Starlight Relay'),
    description: 'A relay team of misfit runners chases a record that hasn\u2019t moved in thirty years.',
    runtime: null,
    episodes: 26,
    playtime: null,
  },
  {
    id: 'demo-anime-2',
    provider: 'demo',
    providerId: 'demo-anime-2',
    title: 'Rust & Bloom',
    originalTitle: 'Sabi to Hana',
    type: 'anime',
    year: 2023,
    rating: 9.0,
    poster: poster('Rust and Bloom'),
    backdrop: backdrop('Rust and Bloom'),
    description: 'In a city rebuilt on the bones of old machines, a gardener discovers her greenhouse is alive.',
    runtime: null,
    episodes: 12,
    playtime: null,
  },
  {
    id: 'demo-anime-3',
    provider: 'demo',
    providerId: 'demo-anime-3',
    title: 'Eleventh Hour Cafe',
    originalTitle: 'Jūichiji no Kissaten',
    type: 'anime',
    year: 2021,
    rating: 7.6,
    poster: poster('Eleventh Hour Cafe'),
    backdrop: backdrop('Eleventh Hour Cafe'),
    description: 'A late-night cafe that only appears to people who need exactly one more conversation that day.',
    runtime: null,
    episodes: 13,
    playtime: null,
  },
  {
    id: 'demo-game-1',
    provider: 'demo',
    providerId: 'demo-game-1',
    title: 'Hollow Meridian',
    originalTitle: 'Hollow Meridian',
    type: 'game',
    year: 2022,
    rating: 8.8,
    poster: poster('Hollow Meridian'),
    backdrop: backdrop('Hollow Meridian'),
    description: 'A metroidvania about a cartographer mapping a continent that keeps rewriting itself.',
    runtime: null,
    episodes: null,
    playtime: 22,
  },
  {
    id: 'demo-game-2',
    provider: 'demo',
    providerId: 'demo-game-2',
    title: 'Driftwood Harbor',
    originalTitle: 'Driftwood Harbor',
    type: 'game',
    year: 2020,
    rating: 7.4,
    poster: poster('Driftwood Harbor'),
    backdrop: backdrop('Driftwood Harbor'),
    description: 'A cozy co-op sim about rebuilding a fishing town, one dock and one recipe at a time.',
    runtime: null,
    episodes: null,
    playtime: 40,
  },
  {
    id: 'demo-game-3',
    provider: 'demo',
    providerId: 'demo-game-3',
    title: 'Signal Loss',
    originalTitle: 'Signal Loss',
    type: 'game',
    year: 2024,
    rating: 8.3,
    poster: poster('Signal Loss'),
    backdrop: backdrop('Signal Loss'),
    description: 'A narrative puzzle game where every save file is a different ending of the same night.',
    runtime: null,
    episodes: null,
    playtime: 9,
  },
];
